version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: jenkins-mern-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: mern-auth
    ports:
      - "27018:27017"
    volumes:
      - jenkins_mongodb_data:/data/db
    networks:
      - jenkins-mern-network

  # Backend API (Built from Dockerfile - Production mode)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: tahabukhari/mern-backend:latest
    container_name: jenkins-mern-backend
    restart: unless-stopped
    environment:
      PORT: 5000
      NODE_ENV: production
      MONGODB_URI: mongodb://mongodb:27017/mern-auth
      JWT_SECRET: jenkins-jwt-secret-key-2024-ci-cd-pipeline
      JWT_EXPIRE: 7d
      CLIENT_URL: http://56.228.10.255:81
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    networks:
      - jenkins-mern-network

  # Frontend React App (Built from Dockerfile - Production mode with Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://56.228.10.255:5001/api
    image: tahabukhari/mern-frontend:latest
    container_name: jenkins-mern-frontend
    restart: unless-stopped
    ports:
      - "81:80"
    depends_on:
      - backend
    networks:
      - jenkins-mern-network

networks:
  jenkins-mern-network:
    driver: bridge

volumes:
  jenkins_mongodb_data:
    driver: local
